import * as attributes from './attributes';
import { DebugConfig } from '../../types/dap/config.types';
import * as validators from '../../tools/validator';
import { ObjectAttributeRule, PropertyNormalizers } from '../../types/tools/validator';

export const debugConfigRule: ObjectAttributeRule<DebugConfig> = validators.object<DebugConfig>({
  [attributes.args.attributeName]: attributes.args.attributeRule,
  [attributes.cwd.attributeName]: attributes.cwd.attributeRule,
  [attributes.env.attributeName]: attributes.env.attributeRule,
  [attributes.hostname.attributeName]: attributes.hostname.attributeRule,
  [attributes.maxChildren.attributeName]: attributes.maxChildren.attributeRule,
  [attributes.name.attributeName]: attributes.name.attributeRule,
  [attributes.noDebug.attributeName]: attributes.noDebug.attributeRule,
  [attributes.openFileOnExit.attributeName]: attributes.openFileOnExit.attributeRule,
  [attributes.port.attributeName]: attributes.port.attributeRule,
  [attributes.program.attributeName]: attributes.program.attributeRule,
  [attributes.request.attributeName]: attributes.request.attributeRule,
  [attributes.runtime.attributeName]: attributes.runtime.attributeRule,
  [attributes.runtimeArgs.attributeName]: attributes.runtimeArgs.attributeRule,
  [attributes.setBreakpoints.attributeName]: attributes.setBreakpoints.attributeRule,
  [attributes.skipFiles.attributeName]: attributes.skipFiles.attributeRule,
  [attributes.skipFunctions.attributeName]: attributes.skipFunctions.attributeRule,
  [attributes.stopOnEntry.attributeName]: attributes.stopOnEntry.attributeRule,
  [attributes.trace.attributeName]: attributes.trace.attributeRule,
  [attributes.type.attributeName]: attributes.type.attributeRule,
  [attributes.useAnnounce.attributeName]: attributes.useAnnounce.attributeRule,
  [attributes.useAutoJumpToError.attributeName]: attributes.useAutoJumpToError.attributeRule,
  [attributes.useDebugDirective.attributeName]: attributes.useDebugDirective.attributeRule,
  [attributes.useIntelliSenseInDebugging.attributeName]: attributes.useIntelliSenseInDebugging.attributeRule,
  [attributes.useLoadedScripts.attributeName]: attributes.useLoadedScripts.attributeRule,
  [attributes.useOutputDebug.attributeName]: attributes.useOutputDebug.attributeRule,
  [attributes.usePerfTips.attributeName]: attributes.usePerfTips.attributeRule,
  [attributes.useUIAVersion.attributeName]: attributes.useUIAVersion.attributeRule,
  [attributes.variableCategories.attributeName]: attributes.variableCategories.attributeRule,

  __filename: validators.string().optional(),
  __languageId: validators.literalUnion('ahk', 'ahk2', 'ah2', 'ahkh', 'ahkh2').optional(),
});
export const debugConfigNormalizer: PropertyNormalizers<DebugConfig> = {
  [attributes.args.attributeName]: attributes.args.attributeNormalizer,
  [attributes.cwd.attributeName]: attributes.cwd.attributeNormalizer,
  [attributes.env.attributeName]: attributes.env.attributeNormalizer,
  [attributes.hostname.attributeName]: attributes.hostname.attributeNormalizer,
  [attributes.maxChildren.attributeName]: attributes.maxChildren.attributeNormalizer,
  [attributes.name.attributeName]: attributes.name.attributeNormalizer,
  [attributes.noDebug.attributeName]: attributes.noDebug.attributeNormalizer,
  [attributes.openFileOnExit.attributeName]: attributes.openFileOnExit.attributeNormalizer,
  [attributes.port.attributeName]: attributes.port.attributeNormalizer,
  [attributes.program.attributeName]: attributes.program.attributeNormalizer,
  [attributes.request.attributeName]: attributes.request.attributeNormalizer,
  [attributes.runtime.attributeName]: attributes.runtime.attributeNormalizer,
  [attributes.runtimeArgs.attributeName]: attributes.runtimeArgs.attributeNormalizer,
  [attributes.setBreakpoints.attributeName]: attributes.setBreakpoints.attributeNormalizer,
  [attributes.skipFiles.attributeName]: attributes.skipFiles.attributeNormalizer,
  [attributes.skipFunctions.attributeName]: attributes.skipFunctions.attributeNormalizer,
  [attributes.stopOnEntry.attributeName]: attributes.stopOnEntry.attributeNormalizer,
  [attributes.trace.attributeName]: attributes.trace.attributeNormalizer,
  [attributes.type.attributeName]: attributes.type.attributeNormalizer,
  [attributes.useAnnounce.attributeName]: attributes.useAnnounce.attributeNormalizer,
  [attributes.useAutoJumpToError.attributeName]: attributes.useAutoJumpToError.attributeNormalizer,
  [attributes.useDebugDirective.attributeName]: attributes.useDebugDirective.attributeNormalizer,
  [attributes.useIntelliSenseInDebugging.attributeName]: attributes.useIntelliSenseInDebugging.attributeNormalizer,
  [attributes.useLoadedScripts.attributeName]: attributes.useLoadedScripts.attributeNormalizer,
  [attributes.useOutputDebug.attributeName]: attributes.useOutputDebug.attributeNormalizer,
  [attributes.usePerfTips.attributeName]: attributes.usePerfTips.attributeNormalizer,
  [attributes.useUIAVersion.attributeName]: attributes.useUIAVersion.attributeNormalizer,
  [attributes.variableCategories.attributeName]: attributes.variableCategories.attributeNormalizer,
};
